name: flutter_weather_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: any
  dio: ^4.0.6
  get_it: ^7.2.0
  date_time: ^0.6.0
  equatable: ^2.0.3
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

